config/routes.rb
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
      get 'tab/:name', :action => 'issue_tab', :as => 'tab'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      match 'bulk_update', :via => [:post, :patch]
    end
    resources :time_entries, :controller => 'timelog', :only => [:new, :create]
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]
  get '/queries/filter', :to => 'queries#filter', :as => 'queries_filter'

  resources :news, :only => [:index, :show, :edit, :update, :destroy, :create, :new]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu, :via => [:get, :post]

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    member do
      # Used when updating the edit form of an existing time entry
      patch 'edit', :to => 'timelog#edit'
    end
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/
  # TODO: delete /time_entries for bulk deletion
  match '/time_entries/destroy', :to => 'timelog#destroy', :via => :delete
  # Used to update the new time entry form
  post '/time_entries/new', :to => 'timelog#new'
  # Used to update the bulk edit time entry form
  post '/time_entries/bulk_edit', :to => 'timelog#bulk_edit'

  get 'projects/:id/activity', :to => 'activities#index', :as => :project_activity
  get 'activity', :to => 'activities#index'

  # repositories routes
  get 'projects/:id/repository/:repository_id/statistics', :to => 'repositories#stats'
  get 'projects/:id/repository/:repository_id/graph', :to => 'repositories#graph'
  post 'projects/:id/repository/:repository_id/fetch_changesets', :to => 'repositories#fetch_changesets'

  get 'projects/:id/repository/:repository_id/revisions/:rev', :to => 'repositories#revision'
  get 'projects/:id/repository/:repository_id/revision', :to => 'repositories#revision'
  post   'projects/:id/repository/:repository_id/revisions/:rev/issues', :to => 'repositories#add_related_issue'
  delete 'projects/:id/repository/:repository_id/revisions/:rev/issues/:issue_id', :to => 'repositories#remove_related_issue'
  get 'projects/:id/repository/:repository_id/revisions', :to => 'repositories#revisions'
  %w(browse show entry raw annotate).each do |action|
    get "projects/:id/repository/:repository_id/revisions/:rev/#{action}(/*path)",
        :controller => 'repositories',
        :action => action,
        :format => 'html',
        :constraints => {:rev => /[a-z0-9\.\-_]+/, :path => /.*/}
  end

  %w(browse entry raw changes annotate).each do |action|
    get "projects/:id/repository/:repository_id/#{action}(/*path)",
        :controller => 'repositories',
        :action => action,
        :format => 'html',
        :constraints => {:path => /.*/}
  end

  get "projects/:id/repository/:repository_id/revisions/:rev/diff(/*path)",
      :to => 'repositories#diff',
      :format => 'html',
      :constraints => {:rev => /[a-z0-9\.\-_]+/, :path => /.*/, :format => /(html|diff)/ }

  get "projects/:id/repository/:repository_id/diff(/*path)",
      :to => 'repositories#diff',
      :format => 'html',
      :constraints => {:path => /.*/, :format => /(html|diff)/ }

  get 'projects/:id/repository/:repository_id/show/*path', :to => 'repositories#show', :format => 'html', :constraints => {:path => /.*/}

  get 'projects/:id/repository/:repository_id', :to => 'repositories#show', :path => nil
  get 'projects/:id/repository', :to => 'repositories#show', :path => nil

  # additional routes for having the file name at the end of url
  get 'attachments/:id/:filename', :to => 'attachments#show', :id => /\d+/, :filename => /.*/, :as => 'named_attachment', :format => 'html'
  get 'attachments/download/:id/:filename', :to => 'attachments#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_attachment'
  get 'attachments/download/:id', :to => 'attachments#download', :id => /\d+/
  get 'attachments/thumbnail/:id(/:size)', :to => 'attachments#thumbnail', :id => /\d+/, :size => /\d+/, :as => 'thumbnail'
  resources :attachments, :only => [:show, :update, :destroy]

  # register plugin object types with ObjectTypeConstraint.register_object_type(PluginModel.name.underscore.pluralize')
  constraints Redmine::Acts::Attachable::ObjectTypeConstraint do
    get 'attachments/:object_type/:object_id/edit', :to => 'attachments#edit_all', :as => :object_attachments_edit
    patch 'attachments/:object_type/:object_id', :to => 'attachments#update_all', :as => :object_attachments
    get 'attachments/:object_type/:object_id/download', :to => 'attachments#download_all', :as => :object_attachments_download
  end

  resources :groups do
    resources :memberships, :controller => 'principal_memberships'
    member do
      get 'autocomplete_for_user'
    end
  end

  get 'groups/:id/users/new', :to => 'groups#new_users', :id => /\d+/, :as => 'new_group_users'
  post 'groups/:id/users', :to => 'groups#add_users', :id => /\d+/, :as => 'group_users'
  delete 'groups/:id/users/:user_id', :to => 'groups#remove_user', :id => /\d+/, :as => 'group_user'

  resources :trackers, :except => :show do
    collection do
      match 'fields', :via => [:get, :post]
    end
  end
  resources :issue_statuses, :except => :show do
    collection do
      post 'update_issue_done_ratio'
    end
  end
  resources :custom_fields, :except => :show do
    resources :enumerations, :controller => 'custom_field_enumerations', :except => [:show, :new, :edit]
    put 'enumerations', :to => 'custom_field_enumerations#update_each'
  end
  resources :roles do
    collection do
      get 'permissions'
      post 'permissions', :to => 'roles#update_permissions'
    end
  end
  resources :enumerations, :except => :show
  match 'enumerations/:type', :to => 'enumerations#index', :via => :get

  get '(projects/:id)/search', :controller => 'search', :action => 'index', :as => 'search'


  get  'mail_handler', :to => 'mail_handler#new'
  post 'mail_handler', :to => 'mail_handler#index'

  get 'admin', :to => 'admin#index'
  get 'admin/projects', :to => 'admin#projects'
  get 'admin/plugins', :to => 'admin#plugins'
  get 'admin/info', :to => 'admin#info'
  post 'admin/test_email', :to => 'admin#test_email', :as => 'test_email'
  post 'admin/default_configuration', :to => 'admin#default_configuration'

  match '/admin/projects_context_menu', :to => 'context_menus#projects', :as => 'projects_context_menu', :via => [:get, :post]

  resources :auth_sources do
    member do
      get 'test_connection', :as => 'try_connection'
    end
    collection do
      get 'autocomplete_for_new_user'
    end
  end

  resources :workflows, only: [:index] do
    collection do
      get 'edit'
      patch 'update'
      get 'permissions'
      patch 'update_permissions'
      get 'copy'
      post 'duplicate'
    end
  end

  match 'settings', :controller => 'settings', :action => 'index', :via => :get
  match 'settings/edit', :controller => 'settings', :action => 'edit', :via => [:get, :post]
  match 'settings/plugin/:id', :controller => 'settings', :action => 'plugin', :via => [:get, :post], :as => 'plugin_settings'

  match 'sys/projects', :to => 'sys#projects', :via => :get
  match 'sys/projects/:id/repository', :to => 'sys#create_project_repository', :via => :post
  match 'sys/fetch_changesets', :to => 'sys#fetch_changesets', :via => [:get, :post]

  match 'uploads', :to => 'attachments#upload', :via => :post

  get 'robots.:format', :to => 'welcome#robots', :constraints => {:format => 'txt'}

  get 'help/wiki_syntax/(:type)', :controller => 'help', :action => 'show_wiki_syntax', :constraints => { :type => /detailed/ }, :as => 'help_wiki_syntax'
  get 'help/code_highlighting', :controller => 'help', :action => 'show_code_highlighting',  :as => 'help_code_highlighting'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

app/models/repository/bazaar.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require 'redmine/scm/adapters/bazaar_adapter'

class Repository::Bazaar < Repository
  validates_presence_of :url, :log_encoding

  def self.human_attribute_name(attribute_key_name, *args)
    attr_name = attribute_key_name.to_s
    if attr_name == "url"
      attr_name = "path_to_repository"
    end
    super(attr_name, *args)
  end

  def self.scm_adapter_class
    Redmine::Scm::Adapters::BazaarAdapter
  end

  def self.scm_name
    'Bazaar'
  end

  def entry(path=nil, identifier=nil)
    scm.bzr_path_encodig = log_encoding
    scm.entry(path, identifier)
  end

  def cat(path, identifier=nil)
    scm.bzr_path_encodig = log_encoding
    scm.cat(path, identifier)
  end

  def annotate(path, identifier=nil)
    scm.bzr_path_encodig = log_encoding
    scm.annotate(path, identifier)
  end

  def diff(path, rev, rev_to)
    scm.bzr_path_encodig = log_encoding
    scm.diff(path, rev, rev_to)
  end

  def scm_entries(path=nil, identifier=nil)
    scm.bzr_path_encodig = log_encoding
    entries = scm.entries(path, identifier)
    if entries
      entries.each do |e|
        next if e.lastrev.revision.blank?

        # Set the filesize unless browsing a specific revision
        if identifier.nil? && e.is_file?
          full_path = File.join(root_url, e.path)
          e.size = File.stat(full_path).size if File.file?(full_path)
        end
        c = Change.
              includes(:changeset).
              where("#{Change.table_name}.revision = ? and #{Changeset.table_name}.repository_id = ?", e.lastrev.revision, id).
              order("#{Changeset.table_name}.revision DESC").
              first
        if c
          e.lastrev.identifier = c.changeset.revision
          e.lastrev.name       = c.changeset.revision
          e.lastrev.author     = c.changeset.committer
        end
      end
    end
    entries
  end
  protected :scm_entries

  def fetch_changesets
    scm.bzr_path_encodig = log_encoding
    scm_info = scm.info
    if scm_info
      # latest revision found in database
      db_revision = latest_changeset ? latest_changeset.revision.to_i : 0
      # latest revision in the repository
      scm_revision = scm_info.lastrev.identifier.to_i
      if db_revision < scm_revision
        logger.debug "Fetching changesets for repository #{url}" if logger && logger.debug?
        identifier_from = db_revision + 1
        while identifier_from <= scm_revision
          # loads changesets by batches of 200
          identifier_to = [identifier_from + 199, scm_revision].min
          revisions = scm.revisions('', identifier_to, identifier_from)
          unless revisions.nil?
            transaction do
              revisions.reverse_each do |revision|
                changeset = Changeset.create(:repository   => self,
                                             :revision     => revision.identifier,
                                             :committer    => revision.author,
                                             :committed_on => revision.time,
                                             :scmid        => revision.scmid,
                                             :comments     => revision.message)

                revision.paths.each do |change|
                  Change.create(:changeset => changeset,
                                :action    => change[:action],
                                :path      => change[:path],
                                :revision  => change[:revision])
                end
              end
            end
          end
          identifier_from = identifier_to + 1
        end
      end
    end
  end
end

app/models/repository/filesystem.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# FileSystem adapter
# File written by Paul Rivier, at Demotera.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require 'redmine/scm/adapters/filesystem_adapter'

class Repository::Filesystem < Repository
  validates_presence_of :url

  def self.human_attribute_name(attribute_key_name, *args)
    attr_name = attribute_key_name.to_s
    if attr_name == "url"
      attr_name = "root_directory"
    end
    super(attr_name, *args)
  end

  def self.scm_adapter_class
    Redmine::Scm::Adapters::FilesystemAdapter
  end

  def self.scm_name
    'Filesystem'
  end

  def supports_history?
    false
  end

  def fetch_changesets
    nil
  end
end

app/views/repositories/_changeset.html.erb
<h2><%= l(:label_revision) %> <%= format_revision(@changeset) %></h2>

<div class="details">
  <h4>
    <%= avatar(@changeset.user) %>
    <%= authoring(@changeset.committed_on, @changeset.author) %>
  </h4>
  <% if @changeset.scmid.present? || @changeset.parents.present? || @changeset.children.present? %>
  <ul class="revision-info">
    <% if @changeset.scmid.present? %>
      <li>
        <strong>ID </strong><%= @changeset.scmid %>
      </li>
    <% end %>
    <% if @changeset.parents.present? %>
      <li>
        <strong><%= l(:label_parent_revision) %></strong>
          <%= @changeset.parents.collect{
                |p| link_to_revision(p, @repository, :text => format_revision(p))
              }.join(", ").html_safe %>
      </li>
    <% end %>
    <% if @changeset.children.present? %>
      <li>
        <strong><%= l(:label_child_revision) %></strong>
         <%= @changeset.children.collect{
                |p| link_to_revision(p, @repository, :text => format_revision(p))
               }.join(", ").html_safe %>
      </li>
    <% end %>
  </ul>
  <% end %>

</div>

<div class="wiki changeset-comments">
  <%= format_changeset_comments @changeset %>
</div>

<% if @changeset.issues.visible.any? || User.current.allowed_to?(:manage_related_issues, @repository.project) %>
  <%= render :partial => 'related_issues' %>
<% end %>

<% if User.current.allowed_to?(:browse_repository, @repository.project) %>
<%
tabs = []
tabs << { name: 'revision', label: :label_change_plural,
          url: { :action => 'revision',
                 :id     => @project,
                 :repository_id => @repository.identifier_param,
                 :path   => nil,
                 :rev    => @changeset.identifier}
        }

tabs << { name: 'diff', label: :label_view_diff,
          url: { :action => 'diff',
                 :id     => @project,
                 :repository_id => @repository.identifier_param,
                 :path   => "",
                 :rev    => @changeset.identifier }
        } if action_name == 'diff' || @changeset.filechanges.any?
%>

<%= render :partial => 'common/tabs', :locals => {:tabs => tabs, :selected_tab => action_name} %>
<% end %>

app/views/repositories/_dir_list.html.erb
<div class="autoscroll">
<table class="list entries" id="browser">
<thead>
<tr id="root">
<th><%= l(:field_name) %></th>
<th><%= l(:field_filesize) %></th>
<% if @repository.report_last_commit %>
<th><%= l(:label_revision)  %></th>
<th><%= l(:label_age)       %></th>
<th><%= l(:field_author)    %></th>
<th><%= l(:field_comments)  %></th>
<% end %>
</tr>
</thead>
<tbody>
<%= render :partial => 'dir_list_content' %>
</tbody>
</table>
</div>

app/views/repositories/_navigation.html.erb
<% content_for :header_tags do %>
  <%= javascript_include_tag 'repository_navigation' %>
<% end %>

<% if @entry && !@entry.is_dir? && @repository.supports_cat? %>
  <% download_label = @entry.size ? "#{l :button_download} (#{number_to_human_size @entry.size})" : l(:button_download) %>
  <%= link_to(sprite_icon('download', download_label),
              {:action => 'raw', :id => @project,
               :repository_id => @repository.identifier_param,
               :path => to_path_param(@path),
               :rev => @rev}, class: 'icon icon-download') %>
<% end %>

<%= link_to sprite_icon('stats', l(:label_statistics)),
            {:action => 'stats', :id => @project, :repository_id => @repository.identifier_param},
            :class => 'icon icon-stats' if @repository.supports_history? %>

<%= actions_dropdown do %>
  <%= link_to_if_authorized sprite_icon('settings', l(:label_settings)),
                            {:controller => 'projects', :action => 'settings', :id => @project, :tab => 'repositories'},
                            :class => 'icon icon-settings' if User.current.allowed_to?(:manage_repository, @project) %>
  <%= link_to sprite_icon('reload', l(:button_fetch_changesets)),
              {:action => :fetch_changesets, :id => @project, :repository_id => @repository.identifier_param},
              :class => 'icon icon-reload', :method => :post if User.current.allowed_to?(:manage_repository, @project) && !Setting.autofetch_changesets? %>
<% end %>

<%= form_tag({:action => controller.action_name,
             :id => @project,
             :repository_id => @repository.identifier_param,
             :path => to_path_param(@path),
             :rev => nil},
            {:method => :get, :id => 'revision_selector'}) do -%>
  <!-- Branches Dropdown -->
  <% if !@repository.branches.nil? && @repository.branches.length > 0 -%>
    | <%= l(:label_branch) %>:
    <%= select_tag :branch,
                   options_for_select([''] + @repository.branches, @rev),
                   :id => 'branch' %>
  <% end -%>

  <% if !@repository.tags.nil? && @repository.tags.length > 0 -%>
    | <%= l(:label_tag) %>:
    <%= select_tag :tag,
                   options_for_select([''] + @repository.tags, @rev),
                   :id => 'tag' %>
  <% end -%>

  <% if @repository.supports_history? %>
    | <%= l(:label_revision) %>:
    <%= text_field_tag 'rev', @rev, :size => 8 %>
  <% end %>
<% end -%>

app/views/repositories/_revision_graph.html.erb
<%= javascript_tag do %>
function revisionGraphHandler(){
  drawRevisionGraph(
    document.getElementById('holder'),
    <%= commits.to_json.html_safe %>,
    <%= space %>
  );
}
$(document).ready(revisionGraphHandler);
$(window).resize(revisionGraphHandler);
<% end %>

<div id="holder" class="revision-graph"></div>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'raphael' %>
  <%= javascript_include_tag 'revision_graph' %>
<% end %>

app/views/repositories/_revisions.html.erb
<%= form_tag(
      {:controller => 'repositories', :action => 'diff', :id => project,
       :repository_id => @repository.identifier_param, :path => to_path_param(path)},
      :method => :get
     ) do %>
<% show_diff = revisions.size > 1 && User.current.allowed_to?(:browse_repository, @repository.project) %>
<% if show_diff %>
<p>
  <%= submit_tag(l(:label_view_diff), :name => nil) %>
</p>
<% end %>
<div class="autoscroll">
<% show_revision_graph = ( @repository.supports_revision_graph? && path.blank? ) %>
<%= if show_revision_graph && revisions && revisions.any?
    indexed_commits, graph_space = index_commits(revisions, @repository.branches) do |scmid|
                             url_for(
                               :controller => 'repositories',
                               :action => 'revision',
                               :id => project,
                               :repository_id => @repository.identifier_param,
                               :rev => scmid)
                         end
    render :partial => 'revision_graph',
         :locals => {
            :commits => indexed_commits,
            :space => graph_space
        }
end %>
<table class="list changesets">
<thead><tr>
<th>#</th>
<th></th>
<th></th>
<th><%= l(:label_date) %></th>
<th><%= l(:field_author) %></th>
<th><%= l(:field_comments) %></th>
</tr></thead>
<tbody>
<% line_num = 1 %>
<% revisions.each do |changeset| %>
<tr class="changeset">
<% id_style = (show_revision_graph ? "padding-left:#{(graph_space + 1) * 20}px" : nil) %>
<%= content_tag(:td, :class => 'id', :style => id_style) do %>
  <%= link_to_revision(changeset, @repository) %>
<% end %>
<td class="checkbox"><%= radio_button_tag('rev', changeset.identifier, (line_num==1), :id => "cb-#{line_num}", :onclick => "$('#cbto-#{line_num+1}').prop('checked',true);") if show_diff && (line_num < revisions.size) %></td>
<td class="checkbox"><%= radio_button_tag('rev_to', changeset.identifier, (line_num==2), :id => "cbto-#{line_num}", :onclick => "if ($('#cb-#{line_num}').prop('checked')) {$('#cb-#{line_num-1}').prop('checked',true);}") if show_diff && (line_num > 1) %></td>
<td class="committed_on"><%= format_time(changeset.committed_on) %></td>
<td class="author"><%= changeset.user.blank? ? changeset.author.to_s.truncate(30) : link_to_user(changeset.user) %></td>
<td class="comments"><%= textilizable(truncate_at_line_break(changeset.comments), :formatting => Setting.commit_logs_formatting?) %></td>
</tr>
<% line_num += 1 %>
<% end %>
</tbody>
</table>
</div>
<% if show_diff %>
<p>
  <%= submit_tag(l(:label_view_diff), :name => nil) %>
</p>
<% end %>
<% end %>

app/views/repositories/add_related_issue.js.erb
<% if @issue %>
  $('#related-issues').html('<%= escape_javascript(render :partial => "related_issues") %>');
  $('#related-issue-<%= @issue.id %>').effect("highlight");
  $('#issue_id').focus();
<% else %>
  alert("<%= raw(escape_javascript(l(:label_issue) + ' ' + l('activerecord.errors.messages.invalid'))) %>");
<% end %>

app/views/repositories/annotate.html.erb
<%= call_hook(:view_repositories_show_contextual, { :repository => @repository, :project => @project }) %>

<div class="contextual">
  <%= render :partial => 'navigation' %>
</div>

<h2 class="breadcrumbs"><%= render :partial => 'breadcrumbs', :locals => { :path => @path, :kind => 'file', :revision => @rev } %></h2>

<%= render :partial => 'link_to_functions' %>

<% if @annotate %>
<% colors = Hash.new {|k,v| k[v] = (k.size % 12) } %>
<div class="autoscroll">
<table class="filecontent annotate syntaxhl">
  <tbody>
    <% line_num = 1; previous_revision = nil %>
    <% syntax_highlight_lines(@path, Redmine::CodesetUtil.to_utf8_by_setting(@annotate.content)).each do |line| %>
      <% revision = @annotate.revisions[line_num - 1] %>
      <% previous_annot = @annotate.previous_annotations[line_num - 1] %>
      <tr id="L<%= line_num %>" class="bloc-<%= revision.nil? ? 0 : colors[revision.identifier || revision.revision] %> <%= previous_revision && revision && revision != previous_revision ? 'bloc-change' : nil%>">
        <th class="line-num"><a href="#L<%= line_num %>" data-txt="<%= line_num %>"></a></th>
        <td class="revision">
          <% if revision && revision != previous_revision %>
            <%= revision.identifier ?
                  link_to_revision(revision, @repository) : format_revision(revision) %>
          <% end %>
        </td>
        <td class="author">
          <% if revision && revision != previous_revision %>
            <% author = Redmine::CodesetUtil.to_utf8(revision.author.to_s,
                                                     @repository.repo_log_encoding) %>
            <%= author.split('<').first %>
          <% end %>
        </td>
        <% if @has_previous %>
        <td class="previous">
          <% if previous_annot && revision && revision != previous_revision %>
            <%= link_to '', {:action => 'annotate', :id => @project, :repository_id => @repository.identifier_param, :path => to_path_param(previous_annot.split[1] || @path), :rev => previous_annot.split[0] }, :title => l(:label_view_previous_annotation), :class => 'icon icon-history' %>
          <% end %>
        </td>
        <% end %>
        <% if line == "\n" or line == "\r\n" %>
        <td class="line-code"><br></td>
        <% else %>
        <td class="line-code"><div><%= line.html_safe %></div></td>
        <% end %>
      </tr>
      <% line_num += 1; previous_revision = revision %>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
<p id="errorExplanation"><%= @error_message %></p>
<% end %>

<% html_title(l(:button_annotate)) -%>

<% content_for :header_tags do %>
<%= stylesheet_link_tag 'scm' %>
<% end %>

app/views/repositories/new.html.erb
<h2><%= l(:label_repository_new) %></h2>

<%= labelled_form_for :repository, @repository, :url => project_repositories_path(@project), :html => {:id => 'repository-form'} do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>